name: Build and Deploy Maven App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -f swipcar/pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: swipcar/target/swipcar*.jar
      - name: Publish to GitHub Packages Maven
        uses: actions/maven-publish@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_name: com.proveedores.swipcar
          package_version: 1.0.0
          repository_url: https://maven.pkg.github.com/${GITHUB_REPO}/
          artifact_id: swipcar
          artifact_file: swipcar/target/swipcar*.jar
